// libs
import Head from "next/head";

//components
import { H1 } from "../components/common/H1/H1";
import { Paragraph } from "../components/common/Paragraph/Paragraph";
import { Button } from "../components/common/Button/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Chestr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>
      <header className='py-8 md:py-16'>
        <div className='container'>
          <div className='flex items-center justify-between'>
            <a href='#' className='w-[120px] md:w-[196px]'>
              <img src={'./logo.svg'} alt='' />
            </a>
            <Button href='#' classname='!px-5 !py-3'>Login</Button>
          </div>
        </div>
      </header>
      <main>
        <section className='py-12 md:py-28'>
          <div className='container'>
            <div className='flex flex-wrap items-center justify-between'>
              <div className='w-full md:w-[50%] order-2'>
                <img className='box-shadow' src={'./images/browser.jpg'} alt='' />
              </div>
              <div className='w-full md:w-[44%] order-1 md:order-3 mb-10 md:0'>
                <H1>Snappy Fast <br /> Shopping Wishlist</H1>
                <Paragraph classname='max-w-[432px]'>
                  Save items into wishlists from any online store, and get notified every time there&apos;s a discount.
                </Paragraph>
                <Button href='#' type='second'>
                  <img src={'./chrome.svg'} alt='' />
                  Get Chestr - It’s Free
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}