// libs
import Head from "next/head";

//components
import { H1 } from "../components/common/H1/H1";
import { Paragraph } from "../components/common/Paragraph/Paragraph";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Chestr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>
      <header>
        <div className='container'>
          <a href='#' className='btn'>Login</a>
        </div>
      </header>
      <main>
        <section className='py-12 md:py-24'>
          <div className='container'>
            <div className='flex items-center justify-between'>
              <div className='w-[46%]'>
                <img src={'./images/browser.jpg'} alt='' />
              </div>
              <div className='w-[46%]'>
                <H1>Snappy Fast Shopping Wishlist</H1>
                <Paragraph>
                  Save items into wishlists from any online store, and get notified every time there's a discount.
                </Paragraph>
                <a href='' className='btn'>Get Chestr - It’s Free</a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}